### PR TITLE
Download external dependencies

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
Do not commit other source files

### CODE REVIEW

**Comment by quantumpencil** [comment]
So, I sort of prefer shipping the dependencies as tar files instead of requiring download, I like the repo to be entirely buildable without a connection and not relying on an external hosting source for a dependency.

 I am open to discussing this though. @Nax what do you think?

**Comment by Nax** [comment]
I understand the rationale of not committing binaries, and I kinda agree with that, but the auto-download feature of cmake is a bit too magical for me. I like having the build be fully reproductible even without access to the internet.

Maybe we can add a "download" cmake target that only downloads the archives as a middle ground? Or maybe we should just rely on the auto-download and move on, I don't know.

However, please keep the URL_HASH param, it's important to ensure consistent and safe builds.

**Comment by julianxhokaxhiu** [comment]
Well, speaking about CMake and download experience, I'm using it in FF7_OpenGL and I never had an issue with it. There is no magic behind it and it's pretty rock stable. Only if your connection cuts out then you may have an issue, but that's because the stream is corrupted.

Speaking about connection, I although agree that is cool to build these sources offline, although nowadays to build something without a connection running it's kinda impossible, you would need it either for one reason or another. So I would not focus really on this topic.

Talking about integrity and hash, I could add the parameter and add a sha256 value I obtain from downloading it, but I usually like to do it only when those hashes are given from the original authors. As there is none, because they are Github tarballs, I don't really think it may make it "safer" to use what I get as sha256. But if you insist I can do so, that's fine for me.

Let me know.

**Comment by Nax** [comment]
I'm good with the download option, but please keep a hash. `URL` without `URL_HASH` is deprecated and outputs a warning, and it's good practice to make sure everyone gets the same file anyway.

**Comment by julianxhokaxhiu** [comment]
@Nax Done!

**Pull request merged**
